### ISSUE TITLE
[Feature suggestion] Sort themes in popup menu

### ISSUE THREAD

**Issue by noyannus** [georapbox/firefox-theme-switcher#2]
Great add-on to test the look of site themes with the most common browser themes! 

However, themes in the popup menu seem to be listed by order of installation. Finding a theme in a longer list of themes thus quickly becomes a nuisance. 

Please consider adding alphabetic (alphanumeric?) sorting of theme names. Unfortunately, there's probably no marker to also sort them into categories like ''dark", "light", or "auto-switching", that I'm aware of -- that would be the cherry on the frosting.

**Comment by tbertels** [comment]
See https://github.com/georapbox/firefox-theme-switcher/pull/3

**Comment by noyannus** [comment]
Thinking it over... You could make that list auto-expand up (down) to screen bottom or firefox window bottom. 

And if you considered sorting into labeled categories ("Light", "Dark", "Auto", other?), make that optional. For those who often switch between two corresponding entries (e.g., "Breeze Light" <=> "Breeze Dark") that would be much more convenient than looking up the 'sibling' theme somewhere else in the list.

To switch from the currently active theme that appears on top (old Mozilla site version) to its 'sibling' (as above, the "Breezes"), the active theme could have a marker (solid border? different background? check mark or bullet or so?) to make it easy to spot, and stays until a change is made.

**Comment by tbertels** [comment]
About frequent switching between light and dark themes (my use case), how about an auto switching feature based on time, like darkreader does it?
https://github.com/darkreader/darkreader/blob/ffb7f5d132717a2956d642cabba33bf946ff1980/src/background/extension.ts#L148-L205

**Comment by georapbox** [comment]
I have created another ticket #4 for updating the UI to display the installed themes in a list. I think we should continue the discussion there as it's the relevant ticket for this.

**Comment by noyannus** [comment]
> About frequent switching between light and dark themes (my use case), how about an auto switching feature based on time, like darkreader does it? [darkreader/darkreader@`ffb7f5d`/src/background/extension.ts#L148-L205](https://github.com/darkreader/darkreader/blob/ffb7f5d132717a2956d642cabba33bf946ff1980/src/background/extension.ts#L148-L205)

That exist already. I am happy with [Yin-Yang ](https://github.com/oskarsh/Yin-Yang)and a [script](https://github.com/oskarsh/Yin-Yang/discussions/191).
