### ISSUE TITLE
Display the themes in an unordered list instead of a select box.

### ISSUE THREAD

**Issue by georapbox** [georapbox/firefox-theme-switcher#4]
Displaying the installed themes in a list instead of select box has the advantage that it requires one click less to select a theme.

For users that have a large list of installed themes, provide basic search functionality.

The UI could look like the screenshot below.

![Screenshot 2023-04-27 at 7 05 03 PM](https://user-images.githubusercontent.com/6596039/234920973-3608913d-25a5-44e4-b71a-1344e8d7c622.png)

**Comment by georapbox** [comment]
The current state of the addon is to display the installed themes in a list. Opening the popup, the enabled theme is listed on top and the rest of the themes are sorted alphabetically. There will also be a search box to offer a basic search functionality that filters out themes by name.

There has been a suggestion to always place Dark, Light and System auto themes on top of the list after the enabled theme as these are the themes that users might probably switch often. Of course this is an assumption. In my case, that's what I mostly do but personally I don't have more than 2 or 3 themes installed, so the list is very short. What do you think about it?

Here's how it could look like.

https://user-images.githubusercontent.com/6596039/235080778-f34898d6-cce0-4c92-b28a-fdf724f94408.mov

There is also a limitation on the popup's maximum height, therefore the themes list also needs to have a max-height so that content does not get out of bounds.

**Comment by georapbox** [comment]
Fixed by #6

**Comment by Jieiku** [comment]
I love all the recent changes, thanks a lot!
